batch_per_epoch: 10
batch_size: 32
ckpt_path: ''
env_key: pong
eps_last_frame: 5000
eps_max: 0.08
eps_min: 0.01
gamma: 0.98
gpus: 0
lr: 0.0005
max_epochs: 10000
mode: train
num_cpu_threads: 16
num_init_states: 2000
onnx_path: ''
replay_size: 50000
save_interval: 20
sync_interval: 1000
