version: '3'
services:
  server:
    build:
      context: docker
      args: 
        workspace: ${workspace}
    environment:
        - DISPLAY=:0
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:${workspace}
      - ${HOME}/.Xauthority:/root/.Xauthority
    ports:
      - "127.0.0.1::8080:8080" 
      - "127.0.0.1::5900:5900" 
      - "127.0.0.1::5901:5901" 